version: '3.8'

services:
  spring-api-image:
    build:
      context: .
      dockerfile: Dockerfile
    image: spring-api-image
    container_name: spring-api-container
    ports:
      - "8003:8003"
    networks:
      - spring-network
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_database:3306/rest_api_db
      SPRING_DATASOURCE_USERNAME: elnuevo
      SPRING_DATASOURCE_PASSWORD: 2007

  mysql:
    image: mysql:latest
    container_name: mysql_database
    environment:
      MYSQL_ROOT_PASSWORD: 1986
      MYSQL_DATABASE: rest_api_db
      MYSQL_USER: elnuevo
      MYSQL_PASSWORD: 2007
    ports:
      - "3306:3306"
    networks:
      - spring-network
    volumes:
      - mysql-volume:/var/lib/mysql

networks:
  spring-network:

volumes:
  mysql-volume:
